### ISSUE TITLE
Posts over 300 characters cause errors

### ISSUE THREAD

**Issue by nfriedly** [mauricerenck/mastodon-to-bluesky#2]
Mastodon has a default limit of 500 characters per post (and I believe the underlying protocol enables even longer posts), whereas bluesky has a limit of 300. 

So, this script should probably split posts > 300 characters into multiple posts for bluesky, with the all subsequent ones being a reply to the first. Maybe add a `(1/2)` and `(2/2)` to the end of each post.

This is the error I got:

```
/config/workspace/mastodon-to-bluesky/node_modules/@atproto/api/dist/index.js:15637
        throw new XRPCError(resCode, res.body.error, res.body.message, res.headers);
              ^

XRPCError: Invalid app.bsky.feed.post record: Record/text must not be longer than 300 graphemes
    at ServiceClient.call (/config/workspace/mastodon-to-bluesky/node_modules/@atproto/api/dist/index.js:15637:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostRecord.create (/config/workspace/mastodon-to-bluesky/node_modules/@atproto/api/dist/index.js:26620:17)
    at async postToBluesky (/config/workspace/mastodon-to-bluesky/main.js:48:3)
    at async fetchNewPosts (/config/workspace/mastodon-to-bluesky/main.js:77:7) {
  status: 400,
  error: 'InvalidRequest',
  success: false,
  headers: {
    'access-control-allow-origin': '*',
    'content-length': '123',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 14 Mar 2024 13:52:26 GMT',
    etag: 'W/"7b-5OYjOucrkx456vG6nIBiH/VZWIA"',
    'keep-alive': 'timeout=90',
    'ratelimit-limit': '5000',
    'ratelimit-policy': '5000;w=3600',
    'ratelimit-remaining': '4994',
    'ratelimit-reset': '1710427946',
    'strict-transport-security': 'max-age=63072000',
    vary: 'Accept-Encoding',
    'x-powered-by': 'Express'
  }
}

Node.js v20.9.0
```

**Comment by coding-lemur** [comment]
@nfriedly the issue should fixed now.
Messages with more than 300 chars truncated with an ellipsis symbol at the end :)

**Comment by parth-chovatiya** [comment]
@mauricerenck @nfriedly @coding-lemur We are still getting an error if we try to share posts via API.
Can you please help me?

**Comment by coding-lemur** [comment]
Many thanks for the information. I will investigating this!

**Comment by coding-lemur** [comment]
Hey @parth-chovatiya. I have just tested posting messages with 350 characters and there was no error.

What kind of error message do you get? Can you describe what you did?

best regards

René
